name: BarBar
options:
  bundleIdPrefix: com.barbar
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  developmentLanguage: en
  localizedStringsOptions:
    defaultRegion: en

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ARCHS: arm64
    ONLY_ACTIVE_ARCH: "NO"

targets:
  BarBar:
    type: application
    platform: macOS
    sources:
      - path: Core
      - path: Modules
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.barbar.app
        PRODUCT_NAME: BarBar
        INFOPLIST_FILE: Core/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Core/Resources/BarBar.entitlements
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
    info:
      path: Core/Resources/Info.plist
      properties:
        CFBundleName: BarBar
        CFBundleDisplayName: BarBar
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
    entitlements:
      path: Core/Resources/BarBar.entitlements
      properties:
        com.apple.security.app-sandbox: false
